# Generated by Django 3.2.3 on 2021-05-30 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Link',
            new_name='Meeting',
        ),
    ]
