# Generated by Django 3.2.3 on 2021-05-30 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0003_meeting_meeting_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='meeting_day',
            field=models.CharField(default='monday', max_length=500),
        ),
    ]
