# Generated by Django 3.2.3 on 2021-05-31 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0004_alter_meeting_meeting_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='participants',
            field=models.CharField(default='noone', max_length=5000),
        ),
    ]
