# Generated by Django 3.2.3 on 2021-05-31 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0005_meeting_participants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='friday',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='monday',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='thursday',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='tuesday',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='wednesday',
        ),
    ]
